;; -*- epa-file-encrypt-to: ("shravantr@gmail.com") -*-

[general]
search_limit = 7
output_directory = "/Users/tatarama/Pictures/"

-----BEGIN PGP MESSAGE-----

hF4D2F4QtLTaudsSAQdAQ09dN8STcT3jbsAiVuSKsU5WbYUUsIlvFC4udofMXTMw
fH63lM2GhlALPG/gSs9Ek4O1o3xZZaN9poSDSwOt/6aCYf4DS0vwrxGy8Ku2Ekpd
1KgBCQIQAl9B5UsKBgG3F9imnH6TBMpPrlRPRkwOQpSbT0mgI8NEze3OMtXXis2H
N72toxSCe+nDA/UT3CxTw/Iv8JicSeHXiAt9YbC3lNixsJooJTUvo3FMGRXcoY1G
HHtU4fIXL0tx5BuG/ffauPdNdSackPE/HRZ8hcFMo0qiOhQqKCbUGq7NRROVS95U
V0n0gxCvsaVvQFIqyH5/vosCCj/C3AK2r/g=
=lBgW
-----END PGP MESSAGE-----
