import = ["/Users/tatarama/.config/alacritty/catppuccin/catppuccin-latte.toml"]

[cursor.style]
shape = "Underline"

[env]
TERM = "xterm-256color"

[font]
size = 14.0

[font.bold]
family = "JetBrains Mono"
style = "Extra Bold"

[font.normal]
family = "JetBrains Mono"
style = "Regular"

[[keyboard.bindings]]
chars = "\u001Bf"
key = "F"
mods = "Alt"

[[keyboard.bindings]]
chars = "\u001Bb"
key = "B"
mods = "Alt"

[[keyboard.bindings]]
chars = "\u001Bd"
key = "D"
mods = "Alt"

[[keyboard.bindings]]
action = "Paste"
key = "V"
mods = "Command"

[[keyboard.bindings]]
action = "Copy"
key = "C"
mods = "Command"

[window]
decorations_theme_variant = "Dark"
opacity = 1.0
startup_mode = "Maximized"
title = "waveparticle"
